import { Product } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "deadpool-flat-brim",
    name: "Deadpool Flat Brim Snapback",
    description: "Black flat brim with white Deadpool logo and printed comic under-bill. Bold, iconic, unmistakable.",
    price: 1500,
    originalPrice: 1900,
    image: "/caps/deadpool-flat-brim.jpg",
    category: "iconic",
    brand: "Marvel",
    isOffer: true,
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    createdAt: "2026-01-01",
  },
  {
    id: "deadpool-trucker",
    name: "Deadpool Trucker Cap",
    description: "Classic trucker silhouette with breathable mesh back and printed Deadpool bill.",
    price: 1300,
    image: "/caps/deadpool-trucker.jpg",
    category: "iconic",
    brand: "Marvel",
    isOffer: false,
    isFeatured: true,
    inStock: true,
    rating: 4.7,
    createdAt: "2026-01-01",
  },
  {
    id: "star-wars-classic",
    name: "Star Wars Classic Cap",
    description: "Embroidered STAR WARS lettering with starship print bill. For the galaxy's finest.",
    price: 1200,
    originalPrice: 1500,
    image: "/caps/star-wars-classic.jpg",
    category: "iconic",
    brand: "Star Wars",
    isOffer: true,
    isFeatured: true,
    inStock: true,
    rating: 4.8,
    createdAt: "2026-01-01",
  },
  {
    id: "batman-comic-print",
    name: "Batman Comic Print Snapback",
    description: "All-over vintage comic print with the Bat emblem front and center. Pure Gotham energy.",
    price: 1800,
    image: "/caps/batman-comic-print.jpg",
    category: "iconic",
    brand: "DC Comics",
    isOffer: false,
    isFeatured: true,
    inStock: true,
    rating: 5.0,
    createdAt: "2026-01-01",
  },
  {
    id: "sf-giants-black",
    name: "SF Giants Black Snapback",
    description: "Classic SF logo in orange on all-black. A Bay Area staple.",
    price: 2500,
    image: "/caps/sf-giants-black.jpg",
    category: "legacy",
    brand: "New Era",
    isOffer: false,
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    createdAt: "2026-01-01",
  },
  {
    id: "nightmare-xmas",
    name: "Nightmare Before Christmas Snapback",
    description: "Jack Skellington grin with purple under-bill. Spooky season all year.",
    price: 1600,
    originalPrice: 2000,
    image: "/caps/nightmare-xmas.jpg",
    category: "iconic",
    brand: "Disney",
    isOffer: true,
    isFeatured: true,
    inStock: true,
    rating: 4.8,
    createdAt: "2026-01-01",
  },
  {
    id: "notre-dame-fighting-irish",
    name: "Notre Dame Fighting Irish Cap",
    description: "Leprechaun embroidery with Mickey detail. Green under-bill. A collector's piece.",
    price: 2200,
    image: "/caps/notre-dame-fighting-irish.jpg",
    category: "legacy",
    brand: "New Era",
    isOffer: false,
    isFeatured: true,
    inStock: true,
    rating: 5.0,
    createdAt: "2026-01-01",
  },
  {
    id: "padres-grey-snapback",
    name: "San Diego Padres Grey Snapback",
    description: "Clean grey with black & blue SD logo. Understated, sleek, sharp.",
    price: 2000,
    originalPrice: 2400,
    image: "/caps/padres-grey-snapback.jpg",
    category: "legacy",
    brand: "New Era",
    isOffer: true,
    isFeatured: false,
    inStock: true,
    rating: 4.6,
    createdAt: "2026-01-01",
  },
  {
    id: "blue-jays-classic",
    name: "Toronto Blue Jays Cap",
    description: "Royal blue with the iconic red maple leaf. Fresh up north.",
    price: 2400,
    image: "/caps/blue-jays-classic.jpg",
    category: "legacy",
    brand: "New Era",
    isOffer: false,
    isFeatured: false,
    inStock: true,
    rating: 4.7,
    createdAt: "2026-01-01",
  },
  {
    id: "hard-rock-floral",
    name: "Hard Rock Atlantic City Floral",
    description: "Tropical floral pattern with embroidered Hard Rock logo. Atlantic City vibes.",
    price: 1400,
    originalPrice: 1800,
    image: "/caps/hard-rock-floral.jpg",
    category: "drip",
    brand: "Hard Rock",
    isOffer: true,
    isFeatured: true,
    inStock: true,
    rating: 4.5,
    createdAt: "2026-01-01",
  },
  {
    id: "celtics-white-snapback",
    name: "Boston Celtics White Snapback",
    description: "White crown with green Celtics emblem and elephant print bill. Crisp.",
    price: 1900,
    image: "/caps/celtics-white-snapback.jpg",
    category: "legacy",
    brand: "New Era",
    isOffer: false,
    isFeatured: false,
    inStock: true,
    rating: 4.8,
    createdAt: "2026-01-01",
  },
  {
    id: "dodgers-blue-classic",
    name: "LA Dodgers Blue Cap",
    description: "The classic. Royal blue with white LA. West Coast royalty.",
    price: 2300,
    image: "/caps/dodgers-blue-classic.jpg",
    category: "legacy",
    brand: "New Era",
    isOffer: false,
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    createdAt: "2026-01-01",
  },
  {
    id: "warriors-blue-snapback",
    name: "Golden State Warriors Snapback",
    description: "Blue with the Bay Bridge logo and rainbow-striped bill. Dubs for life.",
    price: 2200,
    originalPrice: 2600,
    image: "/caps/warriors-blue-snapback.jpg",
    category: "legacy",
    brand: "New Era",
    isOffer: true,
    isFeatured: true,
    inStock: true,
    rating: 4.7,
    createdAt: "2026-01-01",
  },
  {
    id: "pittsburgh-grey-snapback",
    name: "Pittsburgh Grey Snapback",
    description: "Grey crown with embroidered Pittsburgh in gold. Simple, solid, steady.",
    price: 1800,
    image: "/caps/pittsburgh-grey-snapback.jpg",
    category: "legacy",
    brand: "New Era",
    isOffer: false,
    isFeatured: false,
    inStock: true,
    rating: 4.6,
    createdAt: "2026-01-01",
  },
  {
    id: "knicks-orange-black",
    name: "NY Knicks Orange/Black Snapback",
    description: "Structured two-tone with embroidered Knicks crest and NYK side badge.",
    price: 2100,
    image: "/caps/knicks-orange-black.jpg",
    category: "hype",
    brand: "New Era",
    isOffer: false,
    isFeatured: true,
    inStock: true,
    rating: 4.9,
    createdAt: "2026-01-01",
  },
];

export const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "hype", label: "Hype" },
  { id: "iconic", label: "Iconic" },
  { id: "legacy", label: "Legacy" },
  { id: "drip", label: "Drip" },
  { id: "streetwear", label: "Streetwear" },
] as const;

export const OFFER_FILTER = { id: "offers", label: "Offers" } as const;